services:
  - type: web
    name: kharesiya-rag
    runtime: docker
    repo: https://github.com/harshoyobaby-ship-it/knowledge-hub
    branch: main
    rootDir: backend
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: APP_ENV
        value: production
      - key: DEBUG
        value: false
      - key: LLM_PROVIDER
        value: groq
      - key: VECTOR_STORE
        value: pinecone
      - key: USE_CELERY
        value: false
      - key: LOCAL_DEV
        value: false
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        sync: false
